const themes = [
  { bodyBg: '#f3f3f6', messageBg: '#3478F6', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#5A9CFF', fontColor: '#ffffff' },
  { bodyBg: '#e6ecff', messageBg: '#1C4DCB', fontColor: '#ffffff' },
  { bodyBg: '#f0f4ff', messageBg: '#2F6FE4', fontColor: '#ffffff' },
  { bodyBg: '#dce9ff', messageBg: '#1B63D6', fontColor: '#ffffff' },

  { bodyBg: '#f3f3f6', messageBg: '#34D186', fontColor: '#ffffff' },
  { bodyBg: '#e7f9f0', messageBg: '#2BB176', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#4FF1A6', fontColor: '#003322' },
  { bodyBg: '#e6fff1', messageBg: '#3ECC9E', fontColor: '#ffffff' },
  { bodyBg: '#f0fffa', messageBg: '#18B88C', fontColor: '#ffffff' },

  { bodyBg: '#fff5f5', messageBg: '#F63460', fontColor: '#ffffff' },
  { bodyBg: '#f3f3f6', messageBg: '#FF6B81', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#FF8FA3', fontColor: '#660000' },
  { bodyBg: '#ffecec', messageBg: '#E03B55', fontColor: '#ffffff' },
  { bodyBg: '#fff3f3', messageBg: '#CC2A4A', fontColor: '#ffffff' },

  { bodyBg: '#fefbea', messageBg: '#FFD447', fontColor: '#000000' },
  { bodyBg: '#fffaf0', messageBg: '#FFC100', fontColor: '#000000' },
  { bodyBg: '#ffffff', messageBg: '#FFF27A', fontColor: '#333300' },
  { bodyBg: '#fffce5', messageBg: '#FFDA3D', fontColor: '#000000' },
  { bodyBg: '#fffbe9', messageBg: '#FBC02D', fontColor: '#000000' },

  { bodyBg: '#f5f0ff', messageBg: '#9B59FF', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#B884FF', fontColor: '#ffffff' },
  { bodyBg: '#f3f3f6', messageBg: '#7A44DD', fontColor: '#ffffff' },
  { bodyBg: '#ede3ff', messageBg: '#844FFF', fontColor: '#ffffff' },
  { bodyBg: '#f8f0ff', messageBg: '#A371F7', fontColor: '#ffffff' },

  { bodyBg: '#f0fcff', messageBg: '#2CC7F4', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#00B8D4', fontColor: '#ffffff' },
  { bodyBg: '#ecf7f9', messageBg: '#0097A7', fontColor: '#ffffff' },
  { bodyBg: '#e5faff', messageBg: '#00ACC1', fontColor: '#ffffff' },
  { bodyBg: '#e0f9ff', messageBg: '#26C6DA', fontColor: '#ffffff' },

  { bodyBg: '#fff4ec', messageBg: '#FF8C42', fontColor: '#ffffff' },
  { bodyBg: '#fff8f0', messageBg: '#FFA94D', fontColor: '#000000' },
  { bodyBg: '#fff0e6', messageBg: '#FF7043', fontColor: '#ffffff' },
  { bodyBg: '#ffefe0', messageBg: '#FF5722', fontColor: '#ffffff' },
  { bodyBg: '#fff3e0', messageBg: '#F57C00', fontColor: '#ffffff' },

  { bodyBg: '#f8f5ff', messageBg: '#A98BFF', fontColor: '#ffffff' },
  { bodyBg: '#f0f0ff', messageBg: '#CABDFF', fontColor: '#333366' },
  { bodyBg: '#f9f3ff', messageBg: '#C792EA', fontColor: '#ffffff' },
  { bodyBg: '#eee7ff', messageBg: '#AA8FFF', fontColor: '#ffffff' },
  { bodyBg: '#f6efff', messageBg: '#D1B3FF', fontColor: '#000000' },

  { bodyBg: '#ffffff', messageBg: '#000000', fontColor: '#ffffff' },
  { bodyBg: '#000000', messageBg: '#ffffff', fontColor: '#000000' },
  { bodyBg: '#1a1a1a', messageBg: '#e6e6e6', fontColor: '#000000' },
  { bodyBg: '#f2f2f2', messageBg: '#333333', fontColor: '#ffffff' },
  { bodyBg: '#202124', messageBg: '#8ab4f8', fontColor: '#ffffff' },

  { bodyBg: '#ecf0f1', messageBg: '#3498db', fontColor: '#ffffff' },
  { bodyBg: '#2c3e50', messageBg: '#e74c3c', fontColor: '#ffffff' },
  { bodyBg: '#bdc3c7', messageBg: '#2ecc71', fontColor: '#ffffff' },
  { bodyBg: '#f4f6f7', messageBg: '#9b59b6', fontColor: '#ffffff' },
  { bodyBg: '#fdfefe', messageBg: '#f39c12', fontColor: '#000000' },

  { bodyBg: '#e3f2fd', messageBg: '#1976D2', fontColor: '#ffffff' },
  { bodyBg: '#e8f5e9', messageBg: '#388E3C', fontColor: '#ffffff' },
  { bodyBg: '#ffebee', messageBg: '#D32F2F', fontColor: '#ffffff' },
  { bodyBg: '#fffde7', messageBg: '#FBC02D', fontColor: '#000000' },
  { bodyBg: '#f3e5f5', messageBg: '#8E24AA', fontColor: '#ffffff' },

  { bodyBg: '#eceff1', messageBg: '#455A64', fontColor: '#ffffff' },
  { bodyBg: '#f5f5f5', messageBg: '#607D8B', fontColor: '#ffffff' },
  { bodyBg: '#e0f2f1', messageBg: '#00796B', fontColor: '#ffffff' },
  { bodyBg: '#fce4ec', messageBg: '#C2185B', fontColor: '#ffffff' },
  { bodyBg: '#f9fbe7', messageBg: '#AFB42B', fontColor: '#000000' },

  { bodyBg: '#fff8e1', messageBg: '#FFA000', fontColor: '#000000' },
  { bodyBg: '#e8eaf6', messageBg: '#3F51B5', fontColor: '#ffffff' },
  { bodyBg: '#ede7f6', messageBg: '#673AB7', fontColor: '#ffffff' },
  { bodyBg: '#fff3e0', messageBg: '#FB8C00', fontColor: '#000000' },
  { bodyBg: '#edeff0', messageBg: '#00838F', fontColor: '#ffffff' },

  { bodyBg: '#fafafa', messageBg: '#263238', fontColor: '#ffffff' },
  { bodyBg: '#eceff1', messageBg: '#90A4AE', fontColor: '#000000' },
  { bodyBg: '#f0f4c3', messageBg: '#689F38', fontColor: '#000000' },
  { bodyBg: '#fce4ec', messageBg: '#EC407A', fontColor: '#ffffff' },
  { bodyBg: '#ede7f6', messageBg: '#AB47BC', fontColor: '#ffffff' },

  { bodyBg: '#e1f5fe', messageBg: '#039BE5', fontColor: '#ffffff' },
  { bodyBg: '#f1f8e9', messageBg: '#7CB342', fontColor: '#000000' },
  { bodyBg: '#fff9c4', messageBg: '#FDD835', fontColor: '#000000' },
  { bodyBg: '#fbe9e7', messageBg: '#FF7043', fontColor: '#000000' },
  { bodyBg: '#efebe9', messageBg: '#6D4C41', fontColor: '#ffffff' },

  { bodyBg: '#fafafa', messageBg: '#9E9E9E', fontColor: '#000000' },
  { bodyBg: '#eeeeee', messageBg: '#616161', fontColor: '#ffffff' },
  { bodyBg: '#e0e0e0', messageBg: '#212121', fontColor: '#ffffff' },
  { bodyBg: '#f5f5f5', messageBg: '#424242', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#757575', fontColor: '#ffffff' },

  { bodyBg: '#ffccbc', messageBg: '#BF360C', fontColor: '#ffffff' },
  { bodyBg: '#dcedc8', messageBg: '#558B2F', fontColor: '#000000' },
  { bodyBg: '#b2ebf2', messageBg: '#0097A7', fontColor: '#000000' },
  { bodyBg: '#c5cae9', messageBg: '#303F9F', fontColor: '#ffffff' },
  { bodyBg: '#d1c4e9', messageBg: '#512DA8', fontColor: '#ffffff' },

  { bodyBg: '#f0f0f0', messageBg: '#00BCD4', fontColor: '#000000' },
  { bodyBg: '#e0f7fa', messageBg: '#00ACC1', fontColor: '#000000' },
  { bodyBg: '#ffe0b2', messageBg: '#FB8C00', fontColor: '#000000' },
  { bodyBg: '#ffcc80', messageBg: '#F57C00', fontColor: '#000000' },
  { bodyBg: '#e1bee7', messageBg: '#9C27B0', fontColor: '#ffffff' },

  { bodyBg: '#f5f5f5', messageBg: '#673AB7', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#3F51B5', fontColor: '#ffffff' },
  { bodyBg: '#f0f0f0', messageBg: '#009688', fontColor: '#ffffff' },
  { bodyBg: '#e0e0e0', messageBg: '#795548', fontColor: '#ffffff' },
  { bodyBg: '#fafafa', messageBg: '#607D8B', fontColor: '#ffffff' },

  { bodyBg: '#ffffff', messageBg: '#00C853', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#C51162', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#AA00FF', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#6200EA', fontColor: '#ffffff' },
  { bodyBg: '#ffffff', messageBg: '#304FFE', fontColor: '#ffffff' },
];

export default themes;